# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bot_invite.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x62ot_invite.proto\"t\n\ninvite_uid\x12\x0b\n\x03num\x18\x01 \x01(\x05\x12!\n\x04\x46unc\x18\x02 \x01(\x0b\x32\x13.invite_uid.Another\x1a\x36\n\x07\x41nother\x12\x0b\n\x03uid\x18\x01 \x01(\x03\x12\x0e\n\x06region\x18\x02 \x01(\t\x12\x0e\n\x06number\x18\x04 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bot_invite_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_INVITE_UID']._serialized_start=20
  _globals['_INVITE_UID']._serialized_end=136
  _globals['_INVITE_UID_ANOTHER']._serialized_start=82
  _globals['_INVITE_UID_ANOTHER']._serialized_end=136
# @@protoc_insertion_point(module_scope)
