# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bot_mode.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x62ot_mode.proto\"\xa4\x01\n\x07\x42otMode\x12\x0c\n\x04key1\x18\x01 \x01(\x05\x12\x1e\n\x04key2\x18\x02 \x01(\x0b\x32\x10.BotMode.MainFun\x1ak\n\x07MainFun\x12\x0b\n\x03uid\x18\x01 \x01(\x03\x12\x0c\n\x04key2\x18\x02 \x01(\x05\x12\x0c\n\x04key3\x18\x03 \x01(\x05\x12\x0c\n\x04key4\x18\x04 \x01(\x05\x12\x0c\n\x04\x62yte\x18\x05 \x01(\x0c\x12\x0c\n\x04key8\x18\x08 \x01(\x05\x12\r\n\x05key13\x18\r \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bot_mode_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_BOTMODE']._serialized_start=19
  _globals['_BOTMODE']._serialized_end=183
  _globals['_BOTMODE_MAINFUN']._serialized_start=76
  _globals['_BOTMODE_MAINFUN']._serialized_end=183
# @@protoc_insertion_point(module_scope)
