# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: your_file.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fyour_file.proto\"\x96\x04\n\x04Root\x12\x0e\n\x06\x66ield1\x18\x01 \x01(\x05\x12\"\n\x06\x66ield2\x18\x02 \x01(\x0b\x32\x12.Root.NestedObject\x1a\xd9\x03\n\x0cNestedObject\x12\x0e\n\x06\x66ield1\x18\x01 \x01(\x03\x12\x0e\n\x06\x66ield2\x18\x02 \x01(\x03\x12\x0e\n\x06\x66ield3\x18\x03 \x01(\x05\x12\x0e\n\x06\x66ield4\x18\x04 \x01(\t\x12\x0e\n\x06\x66ield5\x18\x05 \x01(\x05\x12\x30\n\x06\x66ield9\x18\t \x01(\x0b\x32 .Root.NestedObject.NestedDetails\x12\x0f\n\x07\x66ield10\x18\n \x01(\t\x12\x31\n\x07\x66ield13\x18\r \x01(\x0b\x32 .Root.NestedObject.NestedOptions\x12\x30\n\x07\x66ield14\x18\x0e \x03(\x0b\x32\x1f.Root.NestedObject.Field14Entry\x1a.\n\x0c\x46ield14Entry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a`\n\rNestedDetails\x12\x0e\n\x06\x66ield1\x18\x01 \x01(\t\x12\x0e\n\x06\x66ield2\x18\x02 \x01(\x03\x12\x0e\n\x06\x66ield4\x18\x04 \x01(\x05\x12\x0e\n\x06\x66ield8\x18\x08 \x01(\t\x12\x0f\n\x07\x66ield10\x18\n \x01(\x05\x1a?\n\rNestedOptions\x12\x0e\n\x06\x66ield1\x18\x01 \x01(\t\x12\x0e\n\x06\x66ield2\x18\x02 \x01(\x05\x12\x0e\n\x06\x66ield3\x18\x03 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'your_file_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ROOT_NESTEDOBJECT_FIELD14ENTRY']._options = None
  _globals['_ROOT_NESTEDOBJECT_FIELD14ENTRY']._serialized_options = b'8\001'
  _globals['_ROOT']._serialized_start=20
  _globals['_ROOT']._serialized_end=554
  _globals['_ROOT_NESTEDOBJECT']._serialized_start=81
  _globals['_ROOT_NESTEDOBJECT']._serialized_end=554
  _globals['_ROOT_NESTEDOBJECT_FIELD14ENTRY']._serialized_start=345
  _globals['_ROOT_NESTEDOBJECT_FIELD14ENTRY']._serialized_end=391
  _globals['_ROOT_NESTEDOBJECT_NESTEDDETAILS']._serialized_start=393
  _globals['_ROOT_NESTEDOBJECT_NESTEDDETAILS']._serialized_end=489
  _globals['_ROOT_NESTEDOBJECT_NESTEDOPTIONS']._serialized_start=491
  _globals['_ROOT_NESTEDOBJECT_NESTEDOPTIONS']._serialized_end=554
# @@protoc_insertion_point(module_scope)
