# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hardest.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rhardest.proto\"\xc4\x06\n\x07hardest\x12\x0e\n\x06\x66ield1\x18\x01 \x01(\x05\x12 \n\x06\x66ield2\x18\x02 \x01(\x0b\x32\x10.hardest.nested2\x1a\x86\x06\n\x07nested2\x12\x0b\n\x03uid\x18\x01 \x01(\x03\x12\x0e\n\x06region\x18\x02 \x01(\t\x12\x0e\n\x06\x66ield3\x18\x03 \x01(\x05\x12\x0e\n\x06\x66ield4\x18\x04 \x01(\x05\x12\x0e\n\x06\x66ield5\x18\x05 \x01(\x0c\x12\x0c\n\x04name\x18\x06 \x01(\t\x12\x0e\n\x06\x66ield7\x18\x07 \x01(\x05\x12\x0e\n\x06\x66ield8\x18\x08 \x01(\x05\x12\x0f\n\x07\x66ield10\x18\n \x01(\t\x12\x0f\n\x07\x66ield11\x18\x0b \x01(\t\x12\x0f\n\x07\x66ield12\x18\x0c \x01(\x05\x12\x0f\n\x07\x66ield13\x18\r \x01(\x03\x12\x0f\n\x07\x66ield16\x18\x10 \x01(\x05\x12*\n\x07\x66ield17\x18\x11 \x01(\x0b\x32\x19.hardest.nested2.nested17\x12\x0f\n\x07\x66ield18\x18\x12 \x01(\x05\x12\x0f\n\x07\x66ield19\x18\x13 \x01(\x05\x12*\n\x07\x66ield20\x18\x14 \x03(\x0b\x32\x19.hardest.nested2.Nested20\x12*\n\x07\x66ield23\x18\x17 \x01(\x0b\x32\x19.hardest.nested2.nested23\x12\x0e\n\x06\x61vatar\x18\x18 \x01(\x03\x12*\n\x07\x66ield26\x18\x1a \x01(\x0b\x32\x19.hardest.nested2.nested26\x12*\n\x07\x66ield28\x18\x1c \x01(\x0b\x32\x19.hardest.nested2.nested28\x1a\x9c\x01\n\x08nested17\x12\x0e\n\x06\x66ield1\x18\x01 \x01(\t\x12\x0e\n\x06\x66ield2\x18\x02 \x01(\x05\x12\x0e\n\x06\x66iled3\x18\x03 \x01(\x0c\x12\x0e\n\x06\x66iled4\x18\x04 \x01(\x0c\x12\x0e\n\x06\x66ield6\x18\x06 \x01(\x05\x12\x0e\n\x06\x66ield7\x18\x07 \x01(\x0c\x12\x0f\n\x07version\x18\x08 \x01(\t\x12\x0e\n\x06\x66ield9\x18\t \x01(\x05\x12\x0f\n\x07\x66ield10\x18\n \x01(\x05\x1a:\n\x08Nested20\x12\x0e\n\x06\x66ield1\x18\x01 \x01(\t\x12\x0e\n\x06\x66ield2\x18\x02 \x01(\x05\x12\x0e\n\x06region\x18\x03 \x01(\t\x1a*\n\x08nested23\x12\x0e\n\x06\x66ield2\x18\x02 \x01(\x05\x12\x0e\n\x06\x66ield3\x18\x03 \x01(\x05\x1a\n\n\x08nested26\x1a\n\n\x08nested28b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hardest_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_HARDEST']._serialized_start=18
  _globals['_HARDEST']._serialized_end=854
  _globals['_HARDEST_NESTED2']._serialized_start=80
  _globals['_HARDEST_NESTED2']._serialized_end=854
  _globals['_HARDEST_NESTED2_NESTED17']._serialized_start=570
  _globals['_HARDEST_NESTED2_NESTED17']._serialized_end=726
  _globals['_HARDEST_NESTED2_NESTED20']._serialized_start=728
  _globals['_HARDEST_NESTED2_NESTED20']._serialized_end=786
  _globals['_HARDEST_NESTED2_NESTED23']._serialized_start=788
  _globals['_HARDEST_NESTED2_NESTED23']._serialized_end=830
  _globals['_HARDEST_NESTED2_NESTED26']._serialized_start=832
  _globals['_HARDEST_NESTED2_NESTED26']._serialized_end=842
  _globals['_HARDEST_NESTED2_NESTED28']._serialized_start=844
  _globals['_HARDEST_NESTED2_NESTED28']._serialized_end=854
# @@protoc_insertion_point(module_scope)
