# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: spam_join.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fspam_join.proto\"\xa2\x02\n\tspam_join\x12\x0f\n\x07\x66ield_1\x18\x01 \x01(\x05\x12\"\n\x07\x66ield_2\x18\x02 \x01(\x0b\x32\x11.spam_join.Nested\x1a\xdf\x01\n\x06Nested\x12\x0f\n\x07\x66ield_1\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\x12.\n\x07\x66ield_3\x18\x03 \x01(\x0b\x32\x1d.spam_join.Nested.InnerNested\x12\x0f\n\x07\x66ield_4\x18\x04 \x01(\x05\x12\x0f\n\x07\x66ield_5\x18\x05 \x01(\x05\x12\x0f\n\x07\x66ield_6\x18\x06 \x01(\x05\x12\x10\n\x08\x66ield_11\x18\x0b \x01(\x03\x12\x10\n\x08\x66ield_12\x18\x0c \x01(\x05\x1a/\n\x0bInnerNested\x12\x0f\n\x07\x66ield_2\x18\x02 \x01(\x05\x12\x0f\n\x07\x66ield_3\x18\x03 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'spam_join_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SPAM_JOIN']._serialized_start=20
  _globals['_SPAM_JOIN']._serialized_end=310
  _globals['_SPAM_JOIN_NESTED']._serialized_start=87
  _globals['_SPAM_JOIN_NESTED']._serialized_end=310
  _globals['_SPAM_JOIN_NESTED_INNERNESTED']._serialized_start=263
  _globals['_SPAM_JOIN_NESTED_INNERNESTED']._serialized_end=310
# @@protoc_insertion_point(module_scope)
